---
- name: AS3 DEPLOY Playbook - STUDENT11
  hosts: localhost
  connection: local
  gather_facts: no

  vars:

  vars_files:
  - ../creds/bigip_creds.yaml
  
  tasks: 

  - name: deploy an app
    uri:
      url: https://20.0.58.197:8443/mgmt/shared/appsvcs/declare
      user: "{{bigip_user}}"
      password: "{{bigip_pass}}"
      method: POST
      body: "{{ lookup('file','as3_declaration.json') }}"
      force_basic_auth: yes
      status_code: 200
      body_format: json
      validate_certs: no
    register: as3_output

  - name: DEBUG output
    debug:
      msg: "OUTPUT {{as3_output}}"
...